options:
  increment_version: false
description: Capture the travels for a station from the web
version: 1.0
params:
  station_number: 8000044
  station_name: Bonn
params_exaples:
  - 8000207, Koeln
  - 8000206, Koblenz
  - 8000044, Bonn
  - 8011160, Berlin
  - 8000105, Frankfurt am Main
  - 8002549, Hamburg Hbf
  - 8000261, München Hbf
  - 8098096, Stuttgart Hbf
  - 8010085, Dresden Hbf
  - 8000240, Mainz Hbf
  - 8000152, Hannover Hbf
  - 8000050, Bremen Hbf
  - 8000085, Düsseldorf Hbf
sources:
  source_name:
    dir: task-001_stations-filtered/
    files: 
    - stations_filtered-all.json
    - stations_filtered-main.json
    - stations_filtered-nrw.json
    route: master
target:
  dir: task-002_station-travels/
  file: travels_$STATION$_$DATE$.log
  route: universe
cmd: python 002.00_main.py station_number=8011160 station_name=Berlin